name: dart2js-size-chart
description: A history of the dart2js size of a tiny Angular.dart app.
version: 0.0.1
author: "James deBoer <james@huronbox.com>"
homepage: https://github.com/jbdeboer/dart2js-size-chart

dependencies:
  angular: any
  browser: any
